### PR TITLE
Change name of app to "modsquad"

### PR DESCRIPTION
**Pull request by waxlamp**
modsquad

### CODE REVIEW

**Comment by waxlamp** [comment]
@jeffbaumes @curtislisle @schloerke @hafen please take a look - not sure if we want the "(by Purdue)" part in there, so let me know what you think.

**Comment by schloerke** [comment]
How about "Purdue ModSquad"?

idk if we want ModSquad or Modsquad.

**Comment by curtislisle** [comment]
I like the camel case of ModSquad.  My intuition would be to have the app name as just ModSquad, and the give credit to the Purdue-led team during the presentation.

**Comment by waxlamp** [comment]
Curt's idea is the simplest and cleanest. I will go with that one and if there are major objections we can just make a change later. Thanks everyone - sorry if I made too big a deal out of this.

**Pull request merged**
