### PR TITLE
Update ta2 output plots

### PR DESCRIPTION
**Pull request by hafen**
Make the ta2 model output plots more "correct". The way they were hastily put together last night didn't make sense.

### CODE REVIEW

**Comment by curtislisle** [comment]
thanks!  I’ll merge this in.  I have a question about the vega CDNS.  They render nicely.  However,  the NIST eval cluster is sequestered without internet access, so we need to add vega via npm install during the docker build.    Is that something you could look at while I keep fighting the pipelines? 

NIST showed sent me a link that brought the interface up.  None of the plotting worked.  However, there was no data.  Between NIST and MIT, they interpret the paths differently.  Here is what the config that NIST presented looked like: (note the datasetDoc.json and problemDoc.json spelled out).  The MIT software excepts pathnames without filenames.  So I’ll add a quick path stemming operation.  


dataset_schema:"/inputs/dataset_TRAIN/datasetDoc.json"
executables_root:"/outputs/executables"
pipeline_logs_root:"/outputs/logs"
problem_root:"/inputs/problem_TRAIN"
problem_schema:"/inputs/problem_TRAIN/problemDoc.json"
ram:"4Gi"
temp_storage_root:"/outputs/temp"
timeout:60
training_data_root:"/inputs/dataset_TRAIN"
user_problems_root:"/outputs/user_problems"

**Comment by hafen** [comment]
Ah I see - I just loaded from CDN as a quick way to not have to spend the time figuring out how to import, but that's been bugging me anyway so I'll try to figure it out right now. The first tab of individual variable visualizations should still render, as they use candela, but I guess if there's no data, nothing would work :).

**Comment by curtislisle** [comment]
the visuals are back now that I have the data config working again.  thanks for looking at the CDN issue.

**Comment by hafen** [comment]
That's good. Will still be an issue on their system. I wish vega/vega-lite/vega-embed supported imports more easily.

**Pull request merged**
